#!/usr/bin/env bash
###############################################
#             __ _               _ _    _     #
#  _ __ ___  / _(_)    __      _(_) | _(_)    #
# | '__/ _ \| |_| |____\ \ /\ / / | |/ / |    #
# | | | (_) |  _| |_____\ V  V /| |   <| |    #
# |_|  \___/|_| |_|      \_/\_/ |_|_|\_\_|    #
#                                             #
###############################################
# This script is a wrapper for rofi that searches the ArchWiki.
# I made this because I wanted to practice bash scripting.
# Something like this may already exist but I do not care.
# Yes the ASCII text above was made with figlet.

set -euo pipefail

lang="en"

mapfile -d $'\0' wikidocs < <(find /usr/share/doc/arch-wiki/html/${lang}/ -iname "*.html" -print0)
# I never knew mapfile was a thing welp.

if [ "$@" ]
then
    xdg-open "$ROFI_INFO"
    exit 0
fi
echo -en "\0prompt\x1fArch wiki\0no-custom\x1ftrue\n" # Set the prompt & disable custom entries

for (( i=0; i<${#wikidocs[@]}; i++ ));
do
    wikidoclink=${wikidocs[i]}
    wikidocs[i]=$(printf '%s' "${wikidocs[i]}" | cut -d '/' -f8- | sed -e 's/.html//g' -e 's/_/ /g')
    echo -en "${wikidocs[i]}\0icon\x1ftext-html\x1finfo\x1f${wikidoclink}\n"
done